/**
 * Station markers for Italy. Data lives in public/data/stations.json (a
 * compact static asset generated by `pnpm run fetch:stations`) and is loaded
 * at runtime so it ships from the CDN instead of the JS bundle.
 */

export interface StationMarker {
  code: string;
  name: string;
  lat: number;
  lon: number;
  isMajor: boolean;
}

type StationTuple = [string, string, number, number, number];

interface StationsJson {
  meta: { count: number; source: string };
  stations: StationTuple[];
}

let cached: StationMarker[] | null = null;
let inFlight: Promise<StationMarker[]> | null = null;

/**
 * Fetch and decode station markers from the compact JSON file.
 * Cached after the first load; retries a few times because a dev-server
 * reload can abort the request.
 */
export async function loadStationMarkers(): Promise<StationMarker[]> {
  if (cached) return cached;
  // Single-flight: concurrent callers share one fetch.
  inFlight ??= fetchAndDecode().finally(() => {
    inFlight = null;
  });
  return inFlight;
}

async function fetchAndDecode(): Promise<StationMarker[]> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch("/data/stations.json");
      if (!res.ok) throw new Error(`Failed to fetch stations: ${res.status}`);
      const data = (await res.json()) as StationsJson;
      cached = data.stations.map(([code, name, lat, lon, major]) => ({
        code,
        name,
        lat,
        lon,
        isMajor: major === 1,
      }));
      return cached;
    } catch (err) {
      lastErr = err;
      if (attempt < 2) {
        await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
      }
    }
  }
  throw lastErr;
}
